# Define custom filters for Digiglass in this YAML file.
# Every field is optional.
#
# Specify a filter to be used during a search like this:
#     digiglass --filter some_new_filter
#
# default_filter is used when no filter is specified.
# Fields not specified in a requested filter use the default filter's settings.

filters:
    my_filter:
        in_stock: true
        lead_free: false
        rohs_compliant: false
        sort_by: '1000011'  # Unit price, USD, ascending
        quantity: 1
    pb_rohs:
        lead_free: true
        rohs_compliant: true

settings:
    default_filter: my_filter
